using NUnit.Framework;

namespace Day8_ResonantCollinearity.Tests;

[TestFixture]
[TestOf(typeof(AntiNodeFinder))]
public class AntiNodeFinderTests
{
    [TestCase("""
              ..........
              ..........
              ..........
              ....a.....
              ..........
              .....a....
              ..........
              ..........
              ..........
              ..........
              """, 2)]
    [TestCase("""
              ..........
              ..........
              ..........
              ....a.....
              ........a.
              .....a....
              ..........
              ..........
              ..........
              ..........
              """, 4)]
    [TestCase("""
              ..........
              ..........
              ..........
              ....a.....
              ........a.
              .....a....
              ..........
              ......A...
              ..........
              ..........
              """, 4)]
    [TestCase("""
              ............
              ........0...
              .....0......
              .......0....
              ....0.......
              ............
              ............
              ............
              ............
              ............
              ............
              ............
              """, 10)]
    [TestCase("""
              ............
              ........0...
              .....0......
              .......0....
              ....0.......
              ......A.....
              ............
              ............
              ........A...
              .........A..
              ............
              ............
              """, 14)]
    public void Test_Examples(string input, int expected)
    {
        var parsedInput = Parser.ParseInput(input);
        Assert.That(AntiNodeFinder.FindAntiNodeCount(parsedInput.gridWidth, parsedInput.gridHeight,
            parsedInput.antennaSets), Is.EqualTo(expected));
    }
    
    [TestCase("""
              T.........
              ...T......
              .T........
              ..........
              ..........
              ..........
              ..........
              ..........
              ..........
              ..........
              """, 9)]
    [TestCase("""
              ............
              ........0...
              .....0......
              .......0....
              ....0.......
              ......A.....
              ............
              ............
              ........A...
              .........A..
              ............
              ............
              """, 34)]
    public void Test_Examples_Part_2(string input, int expected)
    {
        var parsedInput = Parser.ParseInput(input);
        Assert.That(AntiNodeFinder.FindAntiNodeCountWithResonance(parsedInput.gridWidth, parsedInput.gridHeight,
            parsedInput.antennaSets), Is.EqualTo(expected));
    }
}